# Media config:
with_media: false
use_rtsp: false
rtsp_url: ""

# SharedSecret peer config:
shared_secrets: []

# KeyPair peer config:
private_key_file: "/etc/thingify/private_key.json"
trusted_public_keys: []
